name: Build
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  release:

jobs:
  flutter_build_android:
    name: Build Flutter (android) app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11.x"
      - uses: subosito/flutter-action@main
        with:
          cache: true
        name: Fetch Dependencies
      - run: flutter pub get
        name: Build Apk   
      - run: flutter build apk --split-per-abi
      - uses: actions/upload-artifact@v3
        with:
          name: release-builds
          retention-days: 5
          if-no-files-found: warn
          path: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk